'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Check} from 'lucide-react';
import {Product,money} from '@/lib/catalog';
import {ColorPicker} from './product-card';
import {Quantity,useShop} from './shop-provider';
export function ProductDetail({product}:{product:Product}){
 const [colorId,setColorId]=useState(product.colors[0].id),[quantity,setQuantity]=useState(1),[view,setView]=useState('full');const {add}=useShop();
 useEffect(()=>{const c=new URLSearchParams(window.location.search).get('color');if(product.colors.some(x=>x.id===c))setColorId(c!)},[product]);
 const color=product.colors.find(c=>c.id===colorId)!;
 const choose=(id:string)=>{setColorId(id);const u=new URL(window.location.href);u.searchParams.set('color',id);history.replaceState(null,'',u)};
 return <main className="detail-main" id="main"><Link className="back-link" href="/#collection"><ArrowLeft size={16}/> Back to the collection</Link><div className="detail-grid"><div><div className={`detail-image ${product.id} ${view==='detail'?'zoomed':''}`}><img key={`${colorId}-${view}`} src={product.image} style={{filter:color.filter}} alt={`${product.name} ${view==='detail'?'knit detail':'silhouette'} in ${color.name} — concept visualization`}/><span className="image-label">{view==='detail'?'KNIT DETAIL / ENLARGED CROP':'SILHOUETTE STUDY'}</span></div><div className="gallery-buttons" aria-label="Product image views">{['full','detail'].map(v=><button key={v} onClick={()=>setView(v)} aria-pressed={view===v} aria-label={v==='full'?'Show full silhouette':'Show knit detail'}><span className={`thumb-crop ${v}`}><img src={product.image} style={{filter:color.filter}} alt=""/></span>{v==='full'?'The silhouette':'A closer look'}</button>)}</div><p className="image-disclaimer">AI-generated concept imagery. Colors are illustrative; final products may differ.</p></div><div className="detail-copy"><p className="eyebrow">THE FIRST CHAPTER / CONCEPT COLLECTION</p><h1>{product.name}</h1><p className="detail-subtitle">{product.subtitle}</p><div className="price-line"><span>{money(product.price)}</span><span>Sample price · USD</span></div><p className="detail-description">{product.description}</p><div className="color-heading">Color <strong>{color.name}</strong></div><ColorPicker product={product} value={color.id} onChange={choose}/><div className="purchase-row"><Quantity value={quantity} onChange={setQuantity}/><button className="primary-button" onClick={()=>add({productId:product.id,colorId:color.id,quantity})}>Add to bag <ArrowUpRight size={20}/></button></div><p className="purchase-note"><Check size={14}/> Explore the collection. No purchase required.</p><div className="detail-accordions"><details open><summary>Shape & fit</summary><p>{product.silhouette} Final sizing, measurements and fit guidance are still being developed.</p></details><details><summary>Materials & care</summary><p>Yarn composition, patch material and care instructions are pending. The imagery explores a design direction and does not confirm material specifications.</p></details><details><summary>About this preview</summary><p>This is an early shopping prototype. Prices and colors are illustrative. No orders, payments or shipping details are collected.</p></details></div></div></div></main>
}
