import express from 'express';
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import db,{rootDir,uploadDir} from './db.mjs';

const app=express(), dev=process.argv.includes('--dev');
const host=process.env.HOST||'127.0.0.1', port=Number(process.env.PORT||3000), secure=process.env.SESSION_SECURE==='true';
app.disable('x-powered-by');
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');next()});

const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').map(v=>v.trim().split('=').map(decodeURIComponent)).filter(v=>v.length===2));
const session=req=>{const id=cookies(req).lt_session;if(!id)return null;return db.prepare("SELECT s.id,u.id user_id,u.username FROM sessions s JOIN owner_users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>datetime('now')").get(id)};
const requireAuth=(req,res,next)=>{const s=session(req);if(!s)return res.status(401).json({error:'Sign in required.'});req.owner=s;next()};
const sameOrigin=(req,res,next)=>{const origin=req.headers.origin;if(origin&&new URL(origin).host!==req.headers.host)return res.status(403).json({error:'Cross-origin request blocked.'});next()};
app.use('/api',sameOrigin);
app.post('/api/login',express.json(),(req,res)=>{
 const ip=req.ip||'unknown', now=Date.now(), cutoff=now-15*60_000;
 db.prepare('DELETE FROM login_attempts WHERE attempted_at<?').run(cutoff);
 if(db.prepare('SELECT COUNT(*) count FROM login_attempts WHERE ip=?').get(ip).count>=5)return res.status(429).json({error:'Too many attempts. Try again in 15 minutes.'});
 const user=db.prepare('SELECT * FROM owner_users WHERE username=? COLLATE NOCASE').get(String(req.body?.username||''));
 if(!user||!bcrypt.compareSync(String(req.body?.password||''),user.password_hash)){db.prepare('INSERT INTO login_attempts(ip,attempted_at) VALUES(?,?)').run(ip,now);return res.status(401).json({error:'Username or password is incorrect.'})}
 db.prepare('DELETE FROM login_attempts WHERE ip=?').run(ip);const id=crypto.randomBytes(32).toString('hex');db.prepare("INSERT INTO sessions(id,user_id,expires_at) VALUES(?,?,datetime('now','+12 hours'))").run(id,user.id);
 res.setHeader('Set-Cookie',`lt_session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${secure?'; Secure':''}`);res.json({username:user.username});
});
app.post('/api/logout',requireAuth,(req,res)=>{db.prepare('DELETE FROM sessions WHERE id=?').run(req.owner.id);res.setHeader('Set-Cookie','lt_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');res.json({ok:true})});
app.get('/api/session',(req,res)=>{const s=session(req);res.json(s?{authenticated:true,username:s.username}:{authenticated:false})});

app.get('/api/dashboard',requireAuth,(req,res)=>res.json({
 yarns:db.prepare('SELECT COUNT(*) count FROM yarns').get().count,
 skeins:db.prepare('SELECT COALESCE(SUM(quantity_current),0) count FROM purchase_lots').get().count,
 designs:db.prepare('SELECT COUNT(*) count FROM designs').get().count,
 review:db.prepare("SELECT (SELECT COUNT(*) FROM yarns WHERE verification_status='needs_review')+(SELECT COUNT(*) FROM orders WHERE verification_status='needs_review') count").get().count
}));
app.get('/api/categories',requireAuth,(req,res)=>res.json(db.prepare('SELECT * FROM product_categories ORDER BY name').all()));
app.get('/api/yarns',requireAuth,(req,res)=>{const q=`%${String(req.query.q||'').trim()}%`;res.json(db.prepare(`SELECT y.*,COALESCE(SUM(l.quantity_current),0) quantity_current,GROUP_CONCAT(DISTINCT c.name) categories,(SELECT stored_name FROM files WHERE yarn_id=y.id AND kind='yarn_photo' ORDER BY id DESC LIMIT 1) photo FROM yarns y LEFT JOIN purchase_lots l ON l.yarn_id=y.id LEFT JOIN yarn_categories yc ON yc.yarn_id=y.id LEFT JOIN product_categories c ON c.id=yc.category_id WHERE y.brand LIKE ? OR y.line LIKE ? OR y.color_name LIKE ? OR COALESCE(y.sku_upc,'') LIKE ? GROUP BY y.id ORDER BY y.line,y.color_name`).all(q,q,q,q))});
app.get('/api/yarns/:id',requireAuth,(req,res)=>{const yarn=db.prepare('SELECT * FROM yarns WHERE id=?').get(req.params.id);if(!yarn)return res.status(404).json({error:'Yarn not found.'});res.json({...yarn,lots:db.prepare('SELECT l.*,o.vendor,o.order_number FROM purchase_lots l LEFT JOIN orders o ON o.id=l.order_id WHERE yarn_id=? ORDER BY l.id DESC').all(req.params.id),categoryIds:db.prepare('SELECT category_id FROM yarn_categories WHERE yarn_id=?').all(req.params.id).map(r=>r.category_id),files:db.prepare("SELECT id,original_name,mime_type,size,stored_name,created_at FROM files WHERE yarn_id=? AND kind='yarn_photo'").all(req.params.id)})});
const yarnFields=b=>({brand:String(b.brand||'').trim(),line:String(b.line||'').trim(),article:String(b.article||'').trim()||null,color_name:String(b.color_name||'').trim(),color_code:String(b.color_code||'').trim()||null,sku_upc:String(b.sku_upc||'').trim()||null,fiber:String(b.fiber||'').trim()||null,weight:String(b.weight||'').trim()||null,yardage:b.yardage===''||b.yardage==null?null:Number(b.yardage),notes:String(b.notes||'').trim()||null,rating:b.rating==null||b.rating===''?null:Number(b.rating)});
app.post('/api/yarns/duplicates',requireAuth,express.json(),(req,res)=>{const b=yarnFields(req.body||{});const exact=b.sku_upc?db.prepare('SELECT * FROM yarns WHERE sku_upc=?').all(b.sku_upc):[];const partial=db.prepare(`SELECT * FROM yarns WHERE (brand=? COLLATE NOCASE AND line=? COLLATE NOCASE AND color_name=? COLLATE NOCASE) OR (article=? COLLATE NOCASE AND color_code=? COLLATE NOCASE) LIMIT 10`).all(b.brand,b.line,b.color_name,b.article||'',b.color_code||'');res.json({exact,partial:partial.filter(p=>!exact.some(e=>e.id===p.id))})});
app.post('/api/yarns',requireAuth,express.json(),(req,res)=>{const b=yarnFields(req.body||{});if(!b.brand||!b.line||!b.color_name)return res.status(400).json({error:'Brand, yarn line, and color are required.'});if(b.rating!=null&&(b.rating<0||b.rating>5))return res.status(400).json({error:'Rating must be between 0 and 5.'});try{const id=Number(db.transaction(()=>{const r=db.prepare(`INSERT INTO yarns(brand,line,article,color_name,color_code,sku_upc,fiber,weight,yardage,notes,rating) VALUES(@brand,@line,@article,@color_name,@color_code,@sku_upc,@fiber,@weight,@yardage,@notes,@rating)`).run(b);for(const c of req.body.categoryIds||[])db.prepare('INSERT OR IGNORE INTO yarn_categories(yarn_id,category_id) VALUES(?,?)').run(r.lastInsertRowid,c);return r.lastInsertRowid})());res.status(201).json({id})}catch(e){res.status(409).json({error:e.code?.includes('CONSTRAINT')?'A yarn with that SKU/UPC already exists. Add a purchase lot to it instead.':'Unable to add yarn.'})}});
app.put('/api/yarns/:id',requireAuth,express.json(),(req,res)=>{const b=yarnFields(req.body||{});db.transaction(()=>{db.prepare(`UPDATE yarns SET brand=@brand,line=@line,article=@article,color_name=@color_name,color_code=@color_code,sku_upc=@sku_upc,fiber=@fiber,weight=@weight,yardage=@yardage,notes=@notes,rating=@rating,verification_status=COALESCE(@verification_status,verification_status),updated_at=CURRENT_TIMESTAMP WHERE id=@id`).run({...b,id:req.params.id,verification_status:req.body.verification_status||null});db.prepare('DELETE FROM yarn_categories WHERE yarn_id=?').run(req.params.id);for(const c of req.body.categoryIds||[])db.prepare('INSERT INTO yarn_categories(yarn_id,category_id) VALUES(?,?)').run(req.params.id,c)})();res.json({ok:true})});
app.post('/api/yarns/:id/lots',requireAuth,express.json(),(req,res)=>{const b=req.body||{},q=Number(b.quantity_received||0);const r=db.prepare('INSERT INTO purchase_lots(yarn_id,order_id,quantity_ordered,quantity_received,quantity_current,unit_cost_cents,dye_lot,purchase_date,notes) VALUES(?,?,?,?,?,?,?,?,?)').run(req.params.id,b.order_id||null,Number(b.quantity_ordered||q),q,Number(b.quantity_current??q),b.unit_cost_cents||null,b.dye_lot||null,b.purchase_date||null,b.notes||null);res.status(201).json({id:Number(r.lastInsertRowid)})});

app.get('/api/orders',requireAuth,(req,res)=>res.json(db.prepare(`SELECT o.*,COUNT(DISTINCT l.id) lot_count,COUNT(DISTINCT f.id) file_count FROM orders o LEFT JOIN purchase_lots l ON l.order_id=o.id LEFT JOIN files f ON f.order_id=o.id GROUP BY o.id ORDER BY COALESCE(o.order_date,o.created_at) DESC`).all()));
app.post('/api/orders',requireAuth,express.json(),(req,res)=>{const b=req.body||{};if(!String(b.vendor||'').trim())return res.status(400).json({error:'Vendor is required.'});const r=db.prepare('INSERT INTO orders(vendor,order_number,pick_number,alt_po,order_date,total_cents,notes) VALUES(?,?,?,?,?,?,?)').run(String(b.vendor).trim(),b.order_number||null,b.pick_number||null,b.alt_po||null,b.order_date||null,b.total_cents||null,b.notes||null);res.status(201).json({id:Number(r.lastInsertRowid)})});
app.put('/api/orders/:id',requireAuth,express.json(),(req,res)=>{const b=req.body||{};db.prepare('UPDATE orders SET vendor=?,order_number=?,pick_number=?,alt_po=?,order_date=?,total_cents=?,notes=?,verification_status=? WHERE id=?').run(b.vendor,b.order_number||null,b.pick_number||null,b.alt_po||null,b.order_date||null,b.total_cents||null,b.notes||null,b.verification_status||'verified',req.params.id);res.json({ok:true})});

app.get('/api/designs',requireAuth,(req,res)=>res.json(db.prepare(`SELECT d.*,COUNT(dy.yarn_id) compatible_count FROM designs d LEFT JOIN design_yarns dy ON dy.design_id=d.id GROUP BY d.id ORDER BY d.updated_at DESC`).all()));
app.get('/api/designs/:id',requireAuth,(req,res)=>{const d=db.prepare('SELECT * FROM designs WHERE id=?').get(req.params.id);if(!d)return res.status(404).json({error:'Design not found.'});res.json({...d,yarnIds:db.prepare('SELECT yarn_id FROM design_yarns WHERE design_id=?').all(req.params.id).map(r=>r.yarn_id),files:db.prepare("SELECT id,original_name,stored_name,mime_type FROM files WHERE design_id=?").all(req.params.id)})});
app.post('/api/designs',requireAuth,express.json(),(req,res)=>{const b=req.body||{};if(!b.name||!b.architecture)return res.status(400).json({error:'Name and architecture are required.'});const id=Number(db.transaction(()=>{const r=db.prepare('INSERT INTO designs(name,architecture,instructions,tools,sizing,gauge,yardage_requirement,material_requirements,status) VALUES(?,?,?,?,?,?,?,?,?)').run(b.name,b.architecture,b.instructions||'',b.tools||null,b.sizing||null,b.gauge||null,b.yardage_requirement||null,b.material_requirements||null,b.status||'draft');for(const y of b.yarnIds||[])db.prepare('INSERT INTO design_yarns(design_id,yarn_id) VALUES(?,?)').run(r.lastInsertRowid,y);return r.lastInsertRowid})());res.status(201).json({id})});
app.put('/api/designs/:id',requireAuth,express.json(),(req,res)=>{const b=req.body||{};db.transaction(()=>{db.prepare('UPDATE designs SET name=?,architecture=?,instructions=?,tools=?,sizing=?,gauge=?,yardage_requirement=?,material_requirements=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(b.name,b.architecture,b.instructions||'',b.tools||null,b.sizing||null,b.gauge||null,b.yardage_requirement||null,b.material_requirements||null,b.status||'draft',req.params.id);db.prepare('DELETE FROM design_yarns WHERE design_id=?').run(req.params.id);for(const y of b.yarnIds||[])db.prepare('INSERT INTO design_yarns(design_id,yarn_id) VALUES(?,?)').run(req.params.id,y)})();res.json({ok:true})});

const allowed=new Set(['image/jpeg','image/png','image/webp','image/gif','application/pdf']);
app.post('/api/uploads',requireAuth,express.raw({type:()=>true,limit:'20mb'}),async(req,res)=>{const mime=String(req.headers['content-type']||'application/octet-stream').split(';')[0];if(!allowed.has(mime))return res.status(415).json({error:'Upload a JPG, PNG, WebP, GIF, or PDF file.'});const kind=String(req.query.kind||'receipt');if(!['receipt','yarn_photo','design_file'].includes(kind))return res.status(400).json({error:'Invalid upload kind.'});const original=decodeURIComponent(String(req.headers['x-file-name']||'upload'));const ext=mime==='application/pdf'?'.pdf':mime==='image/png'?'.png':mime==='image/webp'?'.webp':mime==='image/gif'?'.gif':'.jpg';const stored=`${crypto.randomUUID()}${ext}`,full=path.join(uploadDir,stored),sha=crypto.createHash('sha256').update(req.body).digest('hex');fs.writeFileSync(full,req.body);const shouldOcr=kind==='receipt';const status=shouldOcr?(mime.startsWith('image/')?'pending':'unsupported'):'not_requested';const r=db.prepare('INSERT INTO files(stored_name,original_name,mime_type,size,sha256,kind,yarn_id,design_id,order_id,ocr_status) VALUES(?,?,?,?,?,?,?,?,?,?)').run(stored,original,mime,req.body.length,sha,kind,req.query.yarnId||null,req.query.designId||null,req.query.orderId||null,status);const id=Number(r.lastInsertRowid);res.status(201).json({id,ocr_status:status});if(status==='pending'){import('tesseract.js').then(async({default:Tesseract})=>{try{const result=await Tesseract.recognize(full,'eng');db.prepare("UPDATE files SET ocr_status='complete',ocr_text=?,ocr_draft=? WHERE id=?").run(result.data.text,JSON.stringify({rawText:result.data.text,confirmed:false}),id)}catch(e){db.prepare("UPDATE files SET ocr_status='failed',ocr_text=? WHERE id=?").run(String(e.message||e),id)}})}});
app.get('/api/files/:stored',requireAuth,(req,res)=>{const f=db.prepare('SELECT * FROM files WHERE stored_name=?').get(req.params.stored);if(!f)return res.status(404).end();res.type(f.mime_type).set('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(f.original_name)}`).sendFile(path.join(uploadDir,f.stored_name))});
app.get('/api/uploads/:id',requireAuth,(req,res)=>{const f=db.prepare('SELECT id,original_name,mime_type,size,kind,ocr_status,ocr_text,ocr_draft,created_at FROM files WHERE id=?').get(req.params.id);if(!f)return res.status(404).json({error:'File not found.'});res.json(f)});
app.put('/api/uploads/:id/ocr',requireAuth,express.json(),(req,res)=>{const draft={...req.body,confirmed:true,confirmedAt:new Date().toISOString()};db.prepare("UPDATE files SET ocr_draft=?,ocr_status=CASE WHEN ocr_status='failed' THEN 'failed' ELSE 'complete' END WHERE id=?").run(JSON.stringify(draft),req.params.id);res.json({ok:true})});

if(dev){const {createServer}=await import('vite');const vite=await createServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares)}else{app.use(express.static(path.join(rootDir,'dist/client'),{index:false}));app.use((req,res)=>res.sendFile(path.join(rootDir,'dist/client/index.html')))}
app.listen(port,host,()=>console.log(`Leather & Thread: http://${host}:${port}`));
