export type Color = { id: string; name: string; hex: string; filter: string };
export type Product = { id: string; name: string; subtitle: string; price: number; image: string; description: string; silhouette: string; colors: Color[] };
export const products: Product[] = [
 {id:'classic-cuff',name:'Classic Cuff',subtitle:'A familiar shape. A fresh start.',price:3200,image:'/images/classic.png',description:'The one you reach for on your way out. A generous folded cuff and a clean, rounded silhouette make this our starting point for everyday warmth.',silhouette:'Rounded crown with a generous folded cuff.',colors:[{id:'cognac',name:'Cognac',hex:'#a05b32',filter:'none'},{id:'charcoal',name:'Charcoal',hex:'#51514b',filter:'grayscale(1) brightness(.65)'},{id:'moss',name:'Moss',hex:'#777451',filter:'hue-rotate(40deg) saturate(.45) brightness(.8)'}]},
 {id:'fisherman',name:'Fisherman',subtitle:'Less length. Plenty of character.',price:3000,image:'/images/fisherman.png',description:'A shorter profile with its own point of view. This compact silhouette brings an easy, understated finish to cold-day layers.',silhouette:'Short crown and shallow cuff; an above-ear look.',colors:[{id:'forest',name:'Forest',hex:'#5e6448',filter:'none'},{id:'ink',name:'Ink',hex:'#41464a',filter:'grayscale(1) brightness(.7)'},{id:'clay',name:'Clay',hex:'#a47761',filter:'sepia(.7) hue-rotate(325deg) saturate(1.6)'}]},
 {id:'slouch',name:'Slouch',subtitle:'Take the long way home.',price:3600,image:'/images/slouch.png',description:'A little room to relax. An extended crown and an easy drape give this concept a softer, more laid-back attitude.',silhouette:'Taller crown with a relaxed, softly falling shape.',colors:[{id:'oat',name:'Oat',hex:'#c4bba3',filter:'none'},{id:'stone',name:'Stone',hex:'#94958e',filter:'grayscale(1) brightness(.75)'},{id:'umber',name:'Umber',hex:'#88705a',filter:'sepia(.5) brightness(.6)'}]},
];
export const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(cents/100);
export const findProduct=(id:string)=>products.find(p=>p.id===id);
